services:
  synclyrics:
    image: sinkuro-backend
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
    build:
      dockerfile: Dockerfile
    ports:
      - "8104:8080"
    depends_on:
      - db

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_DATABASE: synclyrics
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dbdata:/var/lib/mysql
    restart: unless-stopped

volumes:
  db-data: